In [10]:
'''
This is actually the first script, I picked them by hand before, but it provided too little results.

Getting top 50 teams ever that are on the open dota database
'''

'\nThis is actually the first script, I picked them by hand before, but it provided too little results.\n\nGetting top 50 teams ever that are on the open dota database\n'

In [11]:
import json
import numpy as np
import pandas as pd
id_list = list()
team_list = list()

with open('master_team_list.json') as json_data:
    d = json.load(json_data)
    cap = 0
    for record in d:
        if cap < 50:
            id_list.append(record['team_id'])
            team_list.append(record['name'])
            cap = cap + 1
        else:
            break


d = {'team': team_list, 'ID': id_list}
team_df = pd.DataFrame(data=d)

In [12]:
team_df

                          team       ID
0                  Team Liquid     2163
1                  Team Secret  1838315
2                      PSG.LGD       15
3                  Vici Gaming   726228
4                    VGJ Storm  5228654
5                               5026801
6                   Virtus.pro  1883502
7                      Team NP  3214108
8                       Fnatic   350190
9                           OG  2586976
10           (monkey) Business  2519319
11               Evil Geniuses       39
12                 BigGooooood  2101260
13                TNC Predator  2108395
14                   LV-Gaming  1848158
15                       Titan   999689
16                   Winstrike  5229127
17           w33ha earthspirit  4251435
18                    Alliance   111474
19                TeamMalaysia  1910985
20                  Team Aster  6209166
21          Thunder Awaken ///  3922738
22         TEAMERINO TINKERINO  1820360
23   Radical Online X-tremists   293390
24  Speed Gaming International  1047281
25                       EHOME        4
26                    $5JuNGz$  2526472
27                 VGJ Thunder  5027210
28                    Faceless  3326875
29              Forward Gaming  6214538
30                     Signify  5138280
31                 KEEN GAMING  2626685
32                   Team VG.J  3326126
33                      Newbee  1375614
34               Natus Vincere       36
35                   Team Onyx  3722973
36    Orange.Neolution Esports   416900
37           Ninjas in Pyjamas  6214973
38                Team. Spirit  2621843
39                              2635099
40                              2777247
41                              2790766
42                 paiN Gaming       67
43        4 Friends + Chrillee       41
44                     Mineski   543897
45                  Rock.Young  4288603
46              LUCCINI GAM1NG  1025734
47         NAM VEZET-MI IGRAEM  1803996
48       AftershockGaming Int.  1556884
49                      Lajons  2006291

In [15]:
'''
Update the Team list so that I get better ones.
'''
team_df.to_csv('teams.csv', encoding='utf-8', index=False)